### ISSUE TITLE
Requirement.txt not present

### ISSUE THREAD

**Issue by MARafey** [Hassanmustafa786/Ollama#1]
The Readme states that there is a requirement file but its not given in the documents

**Comment by Hassanmustafa786** [comment]
Hi Muhammad Abdur Rafey,

Actually I've lost the requirements.txt file. But here is the link where
you can follow the steps of how to set up the ollama first and then
download the model into the local system:
Running models with Ollama step-by-step | by Gabriel Rodewald | Medium
***@***.***/running-models-with-ollama-step-by-step-60b6f6125807>



After that when you run my code it will ask you to install the packages and
libraries one by one and you have to run the commands with "pip install
<package name>".
I hope this helps.


Regards,
Hassan Mustafa

**Comment by Hassanmustafa786** [comment]
Here is the link from that you can setup ***@***.***/running-models-with-ollama-step-by-step-60b6f6125807Sent from my Galaxy
-------- Original message --------From: Muhammad Abdur Rafey ***@***.***> Date: 30/12/2024  9:42 pm  (GMT+05:00) To: Hassanmustafa786/Ollama ***@***.***> Cc: Hafiz Hassan Mustafa ***@***.***>, Comment ***@***.***> Subject: Re: [Hassanmustafa786/Ollama] Requirement.txt not present (Issue #1) 
Closed #1 as completed.
